language: node_js
sudo: false

node_js:
  - "4"
  - "6"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
